### ISSUE TITLE
mongodb won't start with current mongod.conf

### ISSUE THREAD

**Issue by kmott** [learn-chef/national-parks-java#3]
Hello,

The upstream Habitat core project for mongodb has a config change that removes the `net.http.*` options from mongod.conf, but those changes are not in the `national-parks-java/mongodb` branch.  As a result, mongodb won't start, and throws errors like this:

```
mongodb-parks.default(SV): Starting service as user=hab, group=hab
mongodb-parks.default(O): Unrecognized option: net.http.RESTInterfaceEnabled
mongodb-parks.default(O): try 'mongod --help' for more information
hab-launch(SV): Child for service 'mongodb-parks.default' with PID 2818 exited with code exit code: 2
```

Upstream change: https://github.com/habitat-sh/core-plans/commit/0107fdf12fc5d49ca175e2b97b9679c9a2bf5246

**Comment by drrk** [comment]
Tested the fix, and it's all good.
